export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack Twitter-X with M.E.R.N. Stack.  😍",
		img: "/posts/post1.png",
		user: {
			username: "AkashAich1999",
			profileImg: "/avatars/boy1.png",
			fullName: "Akash Aich",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "Akash.Aich.Developer",
					profileImg: "/avatars/boy3.png",
					fullName: "Akash Aich",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "SahilJha",
			profileImg: "/avatars/boy2.png",
			fullName: "Sahil Jha",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "Akash.Aich.Developer",
					profileImg: "/avatars/boy3.png",
					fullName: "Akash Aich",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
			username: "ManabSaha",
			profileImg: "/avatars/boy1.png",
			fullName: "Manab Saha",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm practicing JS this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
			username: "Akash.Aich.Developer",
			profileImg: "/avatars/boy3.png",
			fullName: "Akash Aich",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "SahilJha",
					profileImg: "/avatars/boy2.png",
					fullName: "Sahil Jha",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "Akash Aich",
		username: "Akash.Aich.Developer",
		profileImg: "/avatars/boy3.png",
	},
	{
		_id: "2",
		fullName: "Yami Gautam",
		username: "yami.gautam",
		profileImg: "/avatars/girl1.png",
	},
	{
		_id: "3",
		fullName: "Sahil Jha",
		username: "SahilJha",
		profileImg: "/avatars/boy2.png",
	},
	{
		_id: "4",
		fullName: "Manab Saha",
		username: "ManabSaha",
		profileImg: "/avatars/boy1.png",
	},
];